S15 cart left
lingsat/freshnesecom pull request #15
Opened 2023-05-30 15:42 UTC by lingsat

2023-05-30 16:11 UTC, Yuliia143 requested changes

2023-05-30 16:11 UTC, Yuliia143 commented on src/features/cart/components/Billing/Billing.tsx
> +        }}>
Logic in JSX!

2023-05-30 18:23 UTC, lingsat commented on src/features/cart/components/Billing/Billing.tsx
> +        }}>
Fixed - replace logic from JSX

2023-05-31 08:34 UTC, Yuliia143 approved these changes

2023-05-31 09:02 UTC, merged